// NisUpscaler.cpp
// NVIDIA Image Scaling (NVScaler) D3D12 integration.
// See NisUpscaler.h for architecture overview.
#include "NisUpscaler.h"
#include "NIS_Config.h"        // NISConfig, NVScalerUpdateConfig, coef_scale, coef_usm

// Compiled shader bytecode (generated by CMake / FXC)
#include "NchwToTexCS.h"
#include "NisMainCS.h"
#include "NisBlitPS.h"
#include "NCHWPresentVS.h"     // fullscreen-triangle VS, reused for blit

#include <stdexcept>
#include <cstring>

// ---------------------------------------------------------------------------
// Helper: align value up to the next multiple of align.
static UINT64 AlignUp(UINT64 v, UINT64 align)
{
    return (v + align - 1) & ~(align - 1);
}

// ---------------------------------------------------------------------------
// Helper: create a static D3D12_STATIC_SAMPLER_DESC (linear clamp at s0).
static D3D12_STATIC_SAMPLER_DESC LinearClampSampler(D3D12_SHADER_VISIBILITY vis)
{
    D3D12_STATIC_SAMPLER_DESC s = {};
    s.Filter           = D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT;
    s.AddressU         = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    s.AddressV         = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    s.AddressW         = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
    s.MaxLOD           = D3D12_FLOAT32_MAX;
    s.ShaderRegister   = 0;
    s.RegisterSpace    = 0;
    s.ShaderVisibility = vis;
    return s;
}

// ===========================================================================
NisUpscaler::NisUpscaler(const D3DContext& ctx,
                         UINT srcW, UINT srcH,
                         UINT dstW, UINT dstH,
                         float sharpness)
    : ctx_(ctx)
    , srcW_(srcW), srcH_(srcH)
    , dstW_(dstW), dstH_(dstH)
{
    auto* dev = ctx_.device12.Get();

    // ── Shader-visible CBV/SRV/UAV heap (7 slots) ──────────────────────────
    {
        D3D12_DESCRIPTOR_HEAP_DESC hd = {};
        hd.Type           = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
        hd.NumDescriptors = HEAP_SLOTS;
        hd.Flags          = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
        HR_CHECK(dev->CreateDescriptorHeap(&hd, IID_PPV_ARGS(&heap_)));
        descSize_ = dev->GetDescriptorHandleIncrementSize(
            D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
    }

    // ── Intermediate textures ───────────────────────────────────────────────
    {
        D3D12_HEAP_PROPERTIES hp = { D3D12_HEAP_TYPE_DEFAULT };
        D3D12_RESOURCE_DESC rd = {};
        rd.Dimension        = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
        rd.Height           = 1;
        rd.DepthOrArraySize = 1;
        rd.MipLevels        = 1;
        rd.Format           = DXGI_FORMAT_R16G16B16A16_FLOAT;
        rd.SampleDesc       = {1, 0};
        rd.Flags            = D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;

        // srcTex: padded NIS input
        rd.Width = srcW;
        rd.Height = srcH;
        HR_CHECK(dev->CreateCommittedResource(&hp, D3D12_HEAP_FLAG_NONE, &rd,
            D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr, IID_PPV_ARGS(&srcTex_)));

        // dstTex: NIS output
        rd.Width = dstW;
        rd.Height = dstH;
        HR_CHECK(dev->CreateCommittedResource(&hp, D3D12_HEAP_FLAG_NONE, &rd,
            D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr, IID_PPV_ARGS(&dstTex_)));
    }

    // ── NISConfig constant buffer (256-byte aligned, persistently mapped) ───
    {
        D3D12_HEAP_PROPERTIES hp = { D3D12_HEAP_TYPE_UPLOAD };
        D3D12_RESOURCE_DESC rd = {};
        rd.Dimension        = D3D12_RESOURCE_DIMENSION_BUFFER;
        rd.Width            = 256;
        rd.Height           = 1;
        rd.DepthOrArraySize = 1;
        rd.MipLevels        = 1;
        rd.SampleDesc       = {1, 0};
        rd.Layout           = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;
        HR_CHECK(dev->CreateCommittedResource(&hp, D3D12_HEAP_FLAG_NONE, &rd,
            D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(&nisCB_)));

        // Compute NISConfig and upload once.
        NISConfig nisConfig = {};
        NVScalerUpdateConfig(nisConfig, sharpness,
            /*inputViewportOriginX*/0, /*Y*/0,
            /*inputViewportW*/srcW, /*H*/srcH,
            /*inputTextureW*/srcW,  /*H*/srcH,
            /*outputViewportOriginX*/0, /*Y*/0,
            /*outputViewportW*/dstW, /*H*/dstH,
            /*outputTextureW*/dstW,  /*H*/dstH,
            NISHDRMode::None);

        void* pMapped = nullptr;
        D3D12_RANGE readRange = {};
        HR_CHECK(nisCB_->Map(0, &readRange, &pMapped));
        std::memcpy(pMapped, &nisConfig, sizeof(nisConfig));
        nisCB_->Unmap(0, nullptr);
    }

    // ── Upload coefficient textures + populate static SRV/UAV descriptors ──
    UploadCoefficients();

    // ── Create fixed SRVs and UAVs in heap ─────────────────────────────────
    // Slot 1: srcTex UAV
    {
        auto h = heap_->GetCPUDescriptorHandleForHeapStart();
        h.ptr += 1 * descSize_;
        D3D12_UNORDERED_ACCESS_VIEW_DESC uavd = {};
        uavd.Format        = DXGI_FORMAT_R16G16B16A16_FLOAT;
        uavd.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
        dev->CreateUnorderedAccessView(srcTex_.Get(), nullptr, &uavd, h);
    }
    // Slot 2: srcTex SRV
    {
        auto h = heap_->GetCPUDescriptorHandleForHeapStart();
        h.ptr += 2 * descSize_;
        D3D12_SHADER_RESOURCE_VIEW_DESC srvd = {};
        srvd.Format                  = DXGI_FORMAT_R16G16B16A16_FLOAT;
        srvd.ViewDimension           = D3D12_SRV_DIMENSION_TEXTURE2D;
        srvd.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
        srvd.Texture2D.MipLevels    = 1;
        dev->CreateShaderResourceView(srcTex_.Get(), &srvd, h);
    }
    // Slot 3: coefScaler SRV
    {
        auto h = heap_->GetCPUDescriptorHandleForHeapStart();
        h.ptr += 3 * descSize_;
        D3D12_SHADER_RESOURCE_VIEW_DESC srvd = {};
        srvd.Format                  = DXGI_FORMAT_R32G32B32A32_FLOAT;
        srvd.ViewDimension           = D3D12_SRV_DIMENSION_TEXTURE2D;
        srvd.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
        srvd.Texture2D.MipLevels    = 1;
        dev->CreateShaderResourceView(coefScalerTex_.Get(), &srvd, h);
    }
    // Slot 4: coefUsm SRV
    {
        auto h = heap_->GetCPUDescriptorHandleForHeapStart();
        h.ptr += 4 * descSize_;
        D3D12_SHADER_RESOURCE_VIEW_DESC srvd = {};
        srvd.Format                  = DXGI_FORMAT_R32G32B32A32_FLOAT;
        srvd.ViewDimension           = D3D12_SRV_DIMENSION_TEXTURE2D;
        srvd.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
        srvd.Texture2D.MipLevels    = 1;
        dev->CreateShaderResourceView(coefUsmTex_.Get(), &srvd, h);
    }
    // Slot 5: dstTex UAV
    {
        auto h = heap_->GetCPUDescriptorHandleForHeapStart();
        h.ptr += 5 * descSize_;
        D3D12_UNORDERED_ACCESS_VIEW_DESC uavd = {};
        uavd.Format        = DXGI_FORMAT_R16G16B16A16_FLOAT;
        uavd.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
        dev->CreateUnorderedAccessView(dstTex_.Get(), nullptr, &uavd, h);
    }
    // Slot 6: dstTex SRV
    {
        auto h = heap_->GetCPUDescriptorHandleForHeapStart();
        h.ptr += 6 * descSize_;
        D3D12_SHADER_RESOURCE_VIEW_DESC srvd = {};
        srvd.Format                  = DXGI_FORMAT_R16G16B16A16_FLOAT;
        srvd.ViewDimension           = D3D12_SRV_DIMENSION_TEXTURE2D;
        srvd.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
        srvd.Texture2D.MipLevels    = 1;
        dev->CreateShaderResourceView(dstTex_.Get(), &srvd, h);
    }

    // ── Build pipelines ─────────────────────────────────────────────────────
    BuildNchwToTexPipeline();
    BuildNisPipeline();
    BuildBlitPipeline();
}

// ---------------------------------------------------------------------------
void NisUpscaler::UploadCoefficients()
{
    // NIS coefficient textures: 2 x 64 pixels, DXGI_FORMAT_R32G32B32A32_FLOAT.
    // coef_scale / coef_usm from NIS_Config.h anonymous namespace.
    // Each physical row = 8 floats stored as 2 float4 texels.
    constexpr UINT kPhaseCount = 64;
    constexpr UINT kWisdom     = 2;   // kFilterSize(8) / 4
    constexpr UINT kBytesPerTexel = 4 * sizeof(float);

    auto* dev   = ctx_.device12.Get();
    auto* queue = ctx_.cmdQueue12.Get();

    // Texture descriptor
    D3D12_RESOURCE_DESC texDesc = {};
    texDesc.Dimension        = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
    texDesc.Width            = kWisdom;
    texDesc.Height           = kPhaseCount;
    texDesc.DepthOrArraySize = 1;
    texDesc.MipLevels        = 1;
    texDesc.Format           = DXGI_FORMAT_R32G32B32A32_FLOAT;
    texDesc.SampleDesc       = {1, 0};
    texDesc.Layout           = D3D12_TEXTURE_LAYOUT_UNKNOWN;

    D3D12_HEAP_PROPERTIES defaultHP = { D3D12_HEAP_TYPE_DEFAULT };
    HR_CHECK(dev->CreateCommittedResource(&defaultHP, D3D12_HEAP_FLAG_NONE, &texDesc,
        D3D12_RESOURCE_STATE_COPY_DEST, nullptr, IID_PPV_ARGS(&coefScalerTex_)));
    HR_CHECK(dev->CreateCommittedResource(&defaultHP, D3D12_HEAP_FLAG_NONE, &texDesc,
        D3D12_RESOURCE_STATE_COPY_DEST, nullptr, IID_PPV_ARGS(&coefUsmTex_)));

    // D3D12 requires upload row pitch aligned to 256.
    const UINT rowStride   = kWisdom * kBytesPerTexel;        // 32 bytes
    const UINT rowPitch256 = static_cast<UINT>(
        AlignUp(rowStride, D3D12_TEXTURE_DATA_PITCH_ALIGNMENT)); // 256 bytes
    const UINT64 uploadSizePerTex = static_cast<UINT64>(rowPitch256) * kPhaseCount;
    const UINT64 totalUpload      = uploadSizePerTex * 2;

    D3D12_HEAP_PROPERTIES uploadHP = { D3D12_HEAP_TYPE_UPLOAD };
    D3D12_RESOURCE_DESC bufDesc = {};
    bufDesc.Dimension        = D3D12_RESOURCE_DIMENSION_BUFFER;
    bufDesc.Width            = totalUpload;
    bufDesc.Height           = 1;
    bufDesc.DepthOrArraySize = 1;
    bufDesc.MipLevels        = 1;
    bufDesc.SampleDesc       = {1, 0};
    bufDesc.Layout           = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;

    ComPtr<ID3D12Resource> uploadBuf;
    HR_CHECK(dev->CreateCommittedResource(&uploadHP, D3D12_HEAP_FLAG_NONE, &bufDesc,
        D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(&uploadBuf)));

    // Map and fill both coefficient arrays
    UINT8* pData = nullptr;
    D3D12_RANGE readRange = {};
    HR_CHECK(uploadBuf->Map(0, &readRange, reinterpret_cast<void**>(&pData)));

    // coef_scale: [kPhaseCount=64][kFilterSize=8 floats] → 2 float4 texels/row
    for (UINT row = 0; row < kPhaseCount; ++row)
    {
        float* rowPtr = reinterpret_cast<float*>(pData + (UINT64)row * rowPitch256);
        for (UINT f = 0; f < 8; ++f)
            rowPtr[f] = coef_scale[row][f];
    }
    // coef_usm: offset by uploadSizePerTex
    for (UINT row = 0; row < kPhaseCount; ++row)
    {
        float* rowPtr = reinterpret_cast<float*>(
            pData + uploadSizePerTex + (UINT64)row * rowPitch256);
        for (UINT f = 0; f < 8; ++f)
            rowPtr[f] = coef_usm[row][f];
    }
    uploadBuf->Unmap(0, nullptr);

    // One-shot command list to copy + transition
    ComPtr<ID3D12CommandAllocator>    alloc;
    ComPtr<ID3D12GraphicsCommandList> cmdList;
    HR_CHECK(dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,
                                         IID_PPV_ARGS(&alloc)));
    HR_CHECK(dev->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT,
                                    alloc.Get(), nullptr, IID_PPV_ARGS(&cmdList)));

    D3D12_TEXTURE_COPY_LOCATION srcLoc = {};
    srcLoc.Type = D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;
    srcLoc.PlacedFootprint.Footprint = {
        DXGI_FORMAT_R32G32B32A32_FLOAT, kWisdom, kPhaseCount, 1, rowPitch256 };
    srcLoc.pResource = uploadBuf.Get();

    D3D12_TEXTURE_COPY_LOCATION dstLoc = {};
    dstLoc.Type              = D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;
    dstLoc.SubresourceIndex  = 0;

    srcLoc.PlacedFootprint.Offset = 0;
    dstLoc.pResource = coefScalerTex_.Get();
    cmdList->CopyTextureRegion(&dstLoc, 0, 0, 0, &srcLoc, nullptr);

    srcLoc.PlacedFootprint.Offset = uploadSizePerTex;
    dstLoc.pResource = coefUsmTex_.Get();
    cmdList->CopyTextureRegion(&dstLoc, 0, 0, 0, &srcLoc, nullptr);

    D3D12_RESOURCE_BARRIER toSRV[2] = {};
    for (int i = 0; i < 2; ++i)
    {
        toSRV[i].Type                   = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
        toSRV[i].Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
        toSRV[i].Transition.StateBefore = D3D12_RESOURCE_STATE_COPY_DEST;
        toSRV[i].Transition.StateAfter  = D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
    }
    toSRV[0].Transition.pResource = coefScalerTex_.Get();
    toSRV[1].Transition.pResource = coefUsmTex_.Get();
    cmdList->ResourceBarrier(2, toSRV);

    HR_CHECK(cmdList->Close());
    ID3D12CommandList* lists[] = { cmdList.Get() };
    queue->ExecuteCommandLists(1, lists);

    // CPU-wait for upload completion before returning.
    ComPtr<ID3D12Fence> fence;
    HR_CHECK(dev->CreateFence(0, D3D12_FENCE_FLAG_NONE, IID_PPV_ARGS(&fence)));
    HANDLE ev = CreateEventW(nullptr, FALSE, FALSE, nullptr);
    HR_CHECK(queue->Signal(fence.Get(), 1));
    if (fence->GetCompletedValue() < 1)
    {
        fence->SetEventOnCompletion(1, ev);
        WaitForSingleObject(ev, INFINITE);
    }
    CloseHandle(ev);
    // uploadBuf released here; GPU is done with it.
}

// ---------------------------------------------------------------------------
void NisUpscaler::BuildNchwToTexPipeline()
{
    auto* dev = ctx_.device12.Get();

    // Root signature:
    //  [0] Root constants (4 uints) at b0   – vidW, vidH, stride, planeSize
    //  [1] SRV table (1 descriptor t0)      – nchwBuf
    //  [2] UAV table (1 descriptor u0)      – srcTex
    D3D12_DESCRIPTOR_RANGE srvRange = {};
    srvRange.RangeType          = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
    srvRange.NumDescriptors     = 1;
    srvRange.BaseShaderRegister = 0;

    D3D12_DESCRIPTOR_RANGE uavRange = {};
    uavRange.RangeType          = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
    uavRange.NumDescriptors     = 1;
    uavRange.BaseShaderRegister = 0;

    D3D12_ROOT_PARAMETER params[3] = {};
    params[0].ParameterType            = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
    params[0].Constants.ShaderRegister = 0;
    params[0].Constants.Num32BitValues = 4;
    params[0].ShaderVisibility         = D3D12_SHADER_VISIBILITY_ALL;

    params[1].ParameterType                       = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    params[1].DescriptorTable.NumDescriptorRanges = 1;
    params[1].DescriptorTable.pDescriptorRanges   = &srvRange;
    params[1].ShaderVisibility                    = D3D12_SHADER_VISIBILITY_ALL;

    params[2].ParameterType                       = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    params[2].DescriptorTable.NumDescriptorRanges = 1;
    params[2].DescriptorTable.pDescriptorRanges   = &uavRange;
    params[2].ShaderVisibility                    = D3D12_SHADER_VISIBILITY_ALL;

    D3D12_ROOT_SIGNATURE_DESC rsDesc = {};
    rsDesc.NumParameters = 3;
    rsDesc.pParameters   = params;

    ComPtr<ID3DBlob> blob, err;
    HR_CHECK(D3D12SerializeRootSignature(&rsDesc, D3D_ROOT_SIGNATURE_VERSION_1,
                                         &blob, &err));
    HR_CHECK(dev->CreateRootSignature(0, blob->GetBufferPointer(),
                                      blob->GetBufferSize(),
                                      IID_PPV_ARGS(&nchwToTexRS_)));

    D3D12_COMPUTE_PIPELINE_STATE_DESC csd = {};
    csd.pRootSignature = nchwToTexRS_.Get();
    csd.CS             = { g_NchwToTexCS, sizeof(g_NchwToTexCS) };
    HR_CHECK(dev->CreateComputePipelineState(&csd, IID_PPV_ARGS(&nchwToTexPSO_)));
}

// ---------------------------------------------------------------------------
void NisUpscaler::BuildNisPipeline()
{
    auto* dev = ctx_.device12.Get();

    // Root signature:
    //  [0] Inline CBV at b0               – NISConfig
    //  [1] SRV table (3 descriptors t0..t2) – in_texture, coef_scaler, coef_usm
    //  [2] UAV table (1 descriptor u0)    – out_texture
    //  Static sampler s0: linear clamp
    D3D12_DESCRIPTOR_RANGE srvRange3 = {};
    srvRange3.RangeType          = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
    srvRange3.NumDescriptors     = 3;
    srvRange3.BaseShaderRegister = 0;

    D3D12_DESCRIPTOR_RANGE uavRange = {};
    uavRange.RangeType          = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
    uavRange.NumDescriptors     = 1;
    uavRange.BaseShaderRegister = 0;

    D3D12_ROOT_PARAMETER params[3] = {};
    params[0].ParameterType             = D3D12_ROOT_PARAMETER_TYPE_CBV;
    params[0].Descriptor.ShaderRegister = 0;
    params[0].ShaderVisibility          = D3D12_SHADER_VISIBILITY_ALL;

    params[1].ParameterType                       = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    params[1].DescriptorTable.NumDescriptorRanges = 1;
    params[1].DescriptorTable.pDescriptorRanges   = &srvRange3;
    params[1].ShaderVisibility                    = D3D12_SHADER_VISIBILITY_ALL;

    params[2].ParameterType                       = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    params[2].DescriptorTable.NumDescriptorRanges = 1;
    params[2].DescriptorTable.pDescriptorRanges   = &uavRange;
    params[2].ShaderVisibility                    = D3D12_SHADER_VISIBILITY_ALL;

    D3D12_STATIC_SAMPLER_DESC staticSampler = LinearClampSampler(D3D12_SHADER_VISIBILITY_ALL);

    D3D12_ROOT_SIGNATURE_DESC rsDesc = {};
    rsDesc.NumParameters     = 3;
    rsDesc.pParameters       = params;
    rsDesc.NumStaticSamplers = 1;
    rsDesc.pStaticSamplers   = &staticSampler;

    ComPtr<ID3DBlob> blob, err;
    HR_CHECK(D3D12SerializeRootSignature(&rsDesc, D3D_ROOT_SIGNATURE_VERSION_1,
                                         &blob, &err));
    HR_CHECK(dev->CreateRootSignature(0, blob->GetBufferPointer(),
                                      blob->GetBufferSize(),
                                      IID_PPV_ARGS(&nisRS_)));

    D3D12_COMPUTE_PIPELINE_STATE_DESC csd = {};
    csd.pRootSignature = nisRS_.Get();
    csd.CS             = { g_NisMainCS, sizeof(g_NisMainCS) };
    HR_CHECK(dev->CreateComputePipelineState(&csd, IID_PPV_ARGS(&nisPSO_)));
}

// ---------------------------------------------------------------------------
void NisUpscaler::BuildBlitPipeline()
{
    auto* dev = ctx_.device12.Get();

    // Root signature:
    //  [0] SRV table (1 descriptor t0) – dstTex
    //  Static sampler s0: linear clamp (pixel visibility)
    D3D12_DESCRIPTOR_RANGE srvRange = {};
    srvRange.RangeType          = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
    srvRange.NumDescriptors     = 1;
    srvRange.BaseShaderRegister = 0;

    D3D12_ROOT_PARAMETER param = {};
    param.ParameterType                       = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
    param.DescriptorTable.NumDescriptorRanges = 1;
    param.DescriptorTable.pDescriptorRanges   = &srvRange;
    param.ShaderVisibility                    = D3D12_SHADER_VISIBILITY_PIXEL;

    D3D12_STATIC_SAMPLER_DESC staticSampler = LinearClampSampler(D3D12_SHADER_VISIBILITY_PIXEL);

    D3D12_ROOT_SIGNATURE_DESC rsDesc = {};
    rsDesc.NumParameters     = 1;
    rsDesc.pParameters       = &param;
    rsDesc.NumStaticSamplers = 1;
    rsDesc.pStaticSamplers   = &staticSampler;
    rsDesc.Flags             = D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT;

    ComPtr<ID3DBlob> blob, err;
    HR_CHECK(D3D12SerializeRootSignature(&rsDesc, D3D_ROOT_SIGNATURE_VERSION_1,
                                         &blob, &err));
    HR_CHECK(dev->CreateRootSignature(0, blob->GetBufferPointer(),
                                      blob->GetBufferSize(),
                                      IID_PPV_ARGS(&blitRS_)));

    D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc = {};
    psoDesc.pRootSignature                         = blitRS_.Get();
    psoDesc.VS                                     = { g_NCHWPresentVS, sizeof(g_NCHWPresentVS) };
    psoDesc.PS                                     = { g_NisBlitPS, sizeof(g_NisBlitPS) };
    psoDesc.RasterizerState.FillMode               = D3D12_FILL_MODE_SOLID;
    psoDesc.RasterizerState.CullMode               = D3D12_CULL_MODE_NONE;
    psoDesc.BlendState.RenderTarget[0].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;
    psoDesc.SampleMask                             = UINT_MAX;
    psoDesc.PrimitiveTopologyType                  = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
    psoDesc.NumRenderTargets                       = 1;
    psoDesc.RTVFormats[0]                          = DXGI_FORMAT_R8G8B8A8_UNORM;
    psoDesc.SampleDesc                             = {1, 0};
    HR_CHECK(dev->CreateGraphicsPipelineState(&psoDesc, IID_PPV_ARGS(&blitPSO_)));
}

// ===========================================================================
void NisUpscaler::Dispatch(ID3D12GraphicsCommandList* cmdList,
                           ID3D12Resource* nchwBuf,
                           UINT vidW, UINT vidH, UINT stride,
                           ID3D12Resource* backBuf,
                           D3D12_CPU_DESCRIPTOR_HANDLE rtvHandle)
{
    auto* dev = ctx_.device12.Get();

    // ── Update slot 0: NCHW buffer SRV ─────────────────────────────────────
    {
        D3D12_SHADER_RESOURCE_VIEW_DESC srvd = {};
        srvd.Format                  = DXGI_FORMAT_R16_FLOAT;
        srvd.ViewDimension           = D3D12_SRV_DIMENSION_BUFFER;
        srvd.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
        srvd.Buffer.NumElements      = 3 * stride * srcH_;
        dev->CreateShaderResourceView(nchwBuf, &srvd,
            heap_->GetCPUDescriptorHandleForHeapStart());
    }

    // ── Set our heap for all three passes ──────────────────────────────────
    ID3D12DescriptorHeap* heaps[] = { heap_.Get() };
    cmdList->SetDescriptorHeaps(1, heaps);

    auto gpuSlot = [&](UINT slot) -> D3D12_GPU_DESCRIPTOR_HANDLE {
        auto h = heap_->GetGPUDescriptorHandleForHeapStart();
        h.ptr += slot * descSize_;
        return h;
    };

    // ===========================================================================
    // Pass 1 – NchwToTex: NCHW buffer → srcTex (UAV)
    // ===========================================================================
    cmdList->SetComputeRootSignature(nchwToTexRS_.Get());
    cmdList->SetPipelineState(nchwToTexPSO_.Get());

    // Root constants: vidW, vidH, stride, planeSize
    UINT planeSize = stride * srcH_;
    UINT constants[4] = { vidW, vidH, stride, planeSize };
    cmdList->SetComputeRoot32BitConstants(0, 4, constants, 0);
    cmdList->SetComputeRootDescriptorTable(1, gpuSlot(0)); // nchwBuf SRV
    cmdList->SetComputeRootDescriptorTable(2, gpuSlot(1)); // srcTex UAV

    UINT dispX = (srcW_ + 7) / 8;
    UINT dispY = (srcH_ + 7) / 8;
    cmdList->Dispatch(dispX, dispY, 1);

    // UAV barrier: wait for srcTex writes, then transition to SRV for NIS.
    {
        D3D12_RESOURCE_BARRIER uavBarrier = {};
        uavBarrier.Type          = D3D12_RESOURCE_BARRIER_TYPE_UAV;
        uavBarrier.UAV.pResource = srcTex_.Get();
        cmdList->ResourceBarrier(1, &uavBarrier);
    }
    {
        D3D12_RESOURCE_BARRIER toSRV = {};
        toSRV.Type                   = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
        toSRV.Transition.pResource   = srcTex_.Get();
        toSRV.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
        toSRV.Transition.StateBefore = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
        toSRV.Transition.StateAfter  = D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
        cmdList->ResourceBarrier(1, &toSRV);
    }

    // ===========================================================================
    // Pass 2 – NIS: srcTex (SRV) → dstTex (UAV)
    // ===========================================================================
    cmdList->SetComputeRootSignature(nisRS_.Get());
    cmdList->SetPipelineState(nisPSO_.Get());

    cmdList->SetComputeRootConstantBufferView(0, nisCB_->GetGPUVirtualAddress());
    cmdList->SetComputeRootDescriptorTable(1, gpuSlot(2)); // srcTex SRV at t0 (+ coef at t1,t2)
    cmdList->SetComputeRootDescriptorTable(2, gpuSlot(5)); // dstTex UAV

    // NIS block dims must match NIS_BLOCK_WIDTH/HEIGHT in shader (default 32x24).
    UINT nisDispX = (dstW_ + 31) / 32;
    UINT nisDispY = (dstH_ + 23) / 24;
    cmdList->Dispatch(nisDispX, nisDispY, 1);

    // Wait for NIS writes, then reset srcTex → UAV and transition dstTex → SRV.
    {
        D3D12_RESOURCE_BARRIER uavBarrier = {};
        uavBarrier.Type          = D3D12_RESOURCE_BARRIER_TYPE_UAV;
        uavBarrier.UAV.pResource = dstTex_.Get();
        cmdList->ResourceBarrier(1, &uavBarrier);
    }
    {
        D3D12_RESOURCE_BARRIER barriers[2] = {};
        // srcTex: SRV → UAV (reset for next frame)
        barriers[0].Type                   = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
        barriers[0].Transition.pResource   = srcTex_.Get();
        barriers[0].Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
        barriers[0].Transition.StateBefore = D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
        barriers[0].Transition.StateAfter  = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
        // dstTex: UAV → SRV (for blit)
        barriers[1].Type                   = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
        barriers[1].Transition.pResource   = dstTex_.Get();
        barriers[1].Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
        barriers[1].Transition.StateBefore = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
        barriers[1].Transition.StateAfter  = D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE;
        cmdList->ResourceBarrier(2, barriers);
    }

    // ===========================================================================
    // Pass 3 – Blit: dstTex (SRV) → backbuffer (RT)
    // ===========================================================================
    // Transition backbuffer PRESENT → RT.
    {
        D3D12_RESOURCE_BARRIER toRT = {};
        toRT.Type                   = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
        toRT.Transition.pResource   = backBuf;
        toRT.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
        toRT.Transition.StateBefore = D3D12_RESOURCE_STATE_PRESENT;
        toRT.Transition.StateAfter  = D3D12_RESOURCE_STATE_RENDER_TARGET;
        cmdList->ResourceBarrier(1, &toRT);
    }

    cmdList->OMSetRenderTargets(1, &rtvHandle, FALSE, nullptr);

    D3D12_VIEWPORT vp = { 0, 0, float(dstW_), float(dstH_), 0, 1 };
    D3D12_RECT     sc = { 0, 0, LONG(dstW_),  LONG(dstH_) };
    cmdList->RSSetViewports(1, &vp);
    cmdList->RSSetScissorRects(1, &sc);
    cmdList->IASetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

    cmdList->SetGraphicsRootSignature(blitRS_.Get());
    cmdList->SetPipelineState(blitPSO_.Get());
    cmdList->SetGraphicsRootDescriptorTable(0, gpuSlot(6)); // dstTex SRV
    cmdList->DrawInstanced(3, 1, 0, 0);

    // Transition dstTex back to UAV, backbuffer to PRESENT.
    {
        D3D12_RESOURCE_BARRIER barriers[2] = {};
        barriers[0].Type                   = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
        barriers[0].Transition.pResource   = dstTex_.Get();
        barriers[0].Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
        barriers[0].Transition.StateBefore = D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE;
        barriers[0].Transition.StateAfter  = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;

        barriers[1].Type                   = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
        barriers[1].Transition.pResource   = backBuf;
        barriers[1].Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
        barriers[1].Transition.StateBefore = D3D12_RESOURCE_STATE_RENDER_TARGET;
        barriers[1].Transition.StateAfter  = D3D12_RESOURCE_STATE_PRESENT;
        cmdList->ResourceBarrier(2, barriers);
    }
}
